### ISSUE TITLE
parameter setting when conbining with datanetAPI

### ISSUE THREAD

**Issue by zzj1hello** [krzysztofrusek/queuinx#2]
Relying on '**examples/QueuingTheory_bootstrap.ipynb**', I replace the 'TM'  **using the datanetAPI**, and i found that the **rho and mu**, which is commented as '#param',  are important to the qos prediction results. 
When the mu is a larger value, the MAPE of delay and jitter is 0.7, 1.6 respectively.
So, how could I get a more similar QT's qos prediction results to the routenet paper?  Thanks a lot !!!

```TM = np.array([T[src, dst]['Flows'][0]['PktsGen'] for src in range(n) for dst in range(n) if src!=dst]) ```

**Comment by krzysztofrusek** [comment]
I think you have a problem with units.
In general, we need the rate to be measured in packets per time unit (e.g. `pkt/s`). The service rate (`mu`) has to be in the same units.
Typically you have arrivals in the correct units but the service can be specified in different ways. The common approach is that you have line speed measured in bits/time units e.g. (`bits/s`) with an optional unit prefix (`M, G`) and packet lengths in bytes `B`. In such a case you must scale the units. Let the line speed be `c` and the average packet length be `l` so` mu=c/(8*l)` in this case.
Note that mu is always the inverse of an average packet service time.
I hope this helps.

**Comment by zzj1hello** [comment]
Thanks for your reply, and I have better **delay results**. But the MAPE of **jitter results** are  still high.
Here, I have `c` ,`AvgPktSize` and  `AvgPktsLambda`, which means average bandwidth for this flow `(bits/time unit)`, average packet size `(bits)` and  average number of packets of average size generated per time unit `(packets/time unit)`. At last, I set the `mu = c * AvgPktsLambda / AvgPktSize`, the gap of delay and jitter  is nearly 30 points and 200 points off the reference value in ON-OFF datasets. 
I tried adjusting parameters such as `buffer_upper_bound` and `fixedpoint model`, but the results couldn't be better. 
Hope to hear your advice again. Thanks a lot !!!


`c=np.array([G.edges[src, dst]['bandwidth'] for src, dst in G.edges()])`
`AvgPktSize = np.array([T[src, dst]['Flows'][0].get('SizeDistParams', {}).get('AvgPktSize', 1000) for src, dst in G.edges()])`
`AvgPktsLambda = np.array([T[src, dst]['Flows'][0]['TimeDistParams'].get('AvgPktsLambda', 1) for src, dst in G.edges()])`

**Comment by krzysztofrusek** [comment]
Usually jitter has higher error, also in this implementation jitter is the variance so make sure the reference is also variance a not std.

I don't understand this part `mu = c * AvgPktsLambda / AvgPktSize`. `AvgPktsLambda` is the rate and the mu should be `mu = c  / AvgPktSize`

regarding `buffer_upper_bound` its a mask parameter and it must grater than any buffer in your network `(>b+1)` so it doesn't affect the results.
